version: "3.7"
services:
    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: findapitch
        volumes:
            - ./api/data:/appdata
        ports:
            - 3306:3306
